### ISSUE TITLE
FlowRouterSSR compatibility

### ISSUE THREAD

**Issue by bensventures** [abecks/meteor-inject-data#1]
Hi,
First of all thanks for forking this and `fast-render` to give support for the latest Meteor changes. I was using the two original packages with the [SSR branch](https://github.com/kadirahq/flow-router/tree/ssr) of FlowRouter but it stopped working with the latest Meteor update.

I've seen you've been able to solve some issue specifically for ReactRouterSSR and I was wondering if FlowRouterSSR could also be looked into?

Right now with your two forked packages, the client side routing works but not the server side rendering.

**Comment by abecks** [comment]
Are you referring to the same issue discussed near the bottom of this thread? https://github.com/meteorhacks/inject-data/pull/11

**Comment by bensventures** [comment]
Yes, I was hoping what was wrong with ReactRouterSSR was the same with FlowRouterSSR and could maybe be fixed in the same way. But I have to admit I don't have much experience with the internals of both packages.

**Comment by abecks** [comment]
If you can create a repo with a sample app showing the problem you are having, I will see if I can fix it

**Comment by bensventures** [comment]
Here is a minimal Meteor project using FlowRouterSSR, FastRender and React: https://github.com/bensventures/flowrouter-ssr-1.4

For SSR to work the routes have to be included both on the client and server, which is the case here. 

You'll notice that if you remove the import of the routes from `server/main.js` you'll see the tag of `inject-data` in the head of the page, but not when the routes are included from the server.

**Comment by abecks** [comment]
This should work in 2.0.5. `staringatlights:inject-data` will now override `meteorhacks:inject-data` if both are included in a project. Other projects will have to update their dependencies to use my packages accordingly.
