### ISSUE TITLE
Issues with FlowRouter SSR 

### ISSUE THREAD

**Issue by SureBro** [abecks/meteor-inject-data#2]
So as we know FlowRouter-SSR has issues with  Meteor 1.4. Routing works fine on the client side. It's the server side that's not working for me. 

It was suggested [here](https://forums.meteor.com/t/what-a-best-alternative-for-flowrouter-now-after-lost-arunoda-and-kadira/31846/69) that adding this package could probably help. It didn't work.

There is difference in behavior though. Before adding this package, I would get an `undefined` error on all routes. Now there's no such error.

I checked the raw file to see whether ssr is working and it's all scripts and no actual html markup.

_**Edit:**_ The error is actually back. Here is all it says, **Error when doing SSR. path:/: undefined**

**Comment by SureBro** [comment]
After a little digging, I have found something. 

This only happens my container components use a "dumb" component to render the UI. If I just put the html markup within the container component instead of using a component, it gets rid of the issue.

**Comment by abecks** [comment]
Can you create a demo app repo that reproduces the issue? I'll see if I can fix it.

**Comment by bensventures** [comment]
@SureBro I've been trying to solve SSR with 1.4 and FlowRouter and forked the original version from Kadira to hack it: https://github.com/bensventures/flow-router I'm using @abecks packages and it seem to solve my problems, maybe give it a try (some instructions in the readme).

**Comment by ziomyslaw** [comment]
@abecks There is an example project with ssr https://github.com/sahanDissanayake/es2015-ssr
It works ok till meteor 1.4.1.3, starting from 1.4.2+ it doesn't generate any html tags inside body. Client side works fine even without inject-data. Adding inject-data doesn't solve the issue. Could you please take a look?

**Comment by SureBro** [comment]
@bensventures I am experiencing a little problem after following the instructions in the readme file. For some reason, Dochead is undefined. 

I followed the instructions:

- removed kadira packages
- added bensventures:flow-router-ssr
- added bensventures:dochead 
- changed all references in react-mounter dist folder from kadira:flow-router-ssr to bensventures:flow-router-ssr

Is there anything I'm missing? I am on 1.4.1.1

**Comment by bensventures** [comment]
@SureBro can you open an issue in my repo? It is probably not related with meteor-inject-data so best to have the discussion on the other one :)

**Comment by SureBro** [comment]
@bensventures Sure
